on:
  push:
    branches:
      - master

env:
  GCP_KEY_ID:  ${{ secrets.GCP_MAIN_SERVICE_ACCOUNT_KEY_ID }}
  GCP_SECRET_KEY:  ${{ secrets.GCP_MAIN_SERVICE_ACCOUNT_SECRET_KEY }}

jobs:

  build-and-deploy:
    name: Deploy Terraform resources to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run unit tests
        run: python -m pytest
          
      - name: Zip up src codes folder
        run: zip -r function-source.zip function-source
      
      - name: list all files
        run: ls

#       - name: Install Terraform
#         uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
